### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'shape'

### ISSUE THREAD

**Issue by ghost** [sgjava/opencv-chip#1]
Howdy

Neat projects you have here, thanks for sharing them. I am a bit over my head but trying this out on my chip and get
```
Traceback (most recent call last):
  File "camerawriter.py", line 49, in <module>
    height, width, unknown = image.shape
AttributeError: 'tuple' object has no attribute 'shape'
```
When I run

`python camerawriter.py http://localhost:8080/?action=stream 200 XVID 5 video-xvid.avi`

I had some issues building opencv with whole enchilada because I forgot to comment out a couple lines further down in config.  I was able to rerun just the opencv install script which succeeded.
I am worried that the enchilada install script may have been cut short when opencv failed the first time.  Short of compiling opencv again I am at a loss of what to do.  Any insight appreciated.

Best regards

**Comment by sgjava** [comment]
My bad, when I refactored mjpegclient out of this project and into motion detector I back ported it here and missed testing it. It returns the raw jpeg and numpy array, thus the tuple error. The correct call is:

jpeg, image = mjpegclient.getFrame(socketFile, boundary)

Do a pull to get the fix.

Also, you can run all the individual scripts as they are designed to uninstall previous versions. Thus, when you want to upgrade to the latest OpenCV you can run install-opencv.sh by itself.

**Comment by ghost** [comment]
Thank you, I was hoping you would be able to spot it right off.

Have a great day
